[package]
name = "color"
author = ["Logan Koester <logan@logankoester.com>"]
version = "0.2.0"
homepage = "https://smaug.dev/packages/color"
keywords = ["colors"]

requires = [
  "smaug/color/lib/color.rb",
  "smaug/color/lib/color/rgb.rb",
  "smaug/color/lib/color/hsl.rb",
  "smaug/color/lib/color/string.rb",
  "smaug/color/lib/color/palette.rb",
  "smaug/color/lib/color/hash.rb",
  "smaug/color/lib/color/matcher.rb"
]

# Which files do you want to be automatically required from your package.
# requires = ["lib/library.rb"]

[package.installs]

# Example
#
# <from> = <to>
# "lib/library.rb" = "app/lib/library.rb"

[dragonruby]
version = "2"
edition = "standard"
