# This file was automatically @generated by Smaug.
# Do not manually edit this file. Edit Smaug.toml instead.

require "smaug/draco/lib/draco.rb"
require "app/components/index.rb"
require "app/entities/index.rb"
require "app/systems/index.rb"
require "app/worlds/index.rb"
require "smaug/color/lib/color.rb"
require "smaug/color/lib/color/rgb.rb"
require "smaug/color/lib/color/hsl.rb"
require "smaug/color/lib/color/string.rb"
require "smaug/color/lib/color/palette.rb"
require "smaug/color/lib/color/hash.rb"
require "smaug/color/lib/color/matcher.rb"
require "app/components/common/index.rb"
require "app/entities/common/index.rb"
require "app/systems/common/index.rb"
require "app/worlds/common/index.rb"
require "smaug/draco-camera/lib/draco_camera.rb"
require "app/components/camera/index.rb"
require "app/entities/camera/index.rb"
require "app/systems/camera/index.rb"

