# This file was automatically @generated by Smaug.
# Do not manually edit this file. Edit Smaug.toml instead.

require "smaug/color/lib/color.rb"
require "smaug/color/lib/color/rgb.rb"
require "smaug/color/lib/color/hsl.rb"
require "smaug/color/lib/color/string.rb"
require "smaug/color/lib/color/palette.rb"
require "smaug/color/lib/color/hash.rb"
require "smaug/color/lib/color/matcher.rb"

