[project]
# The name of your game's executable. This should only contain a-z, A-Z, 0-9, _ or -.
name = "color-example"
# The game's title. This will show up in the tile bar of your executable.
title = "color-example"
version = "0.1.0"
authors = ["Logan Koester <logan@logankoester.com>"]
icon = "metadata/icon.png"
compile_ruby = false

[dragonruby]
version = "3.4"
edition = "pro"

[dependencies]
color = "../"

[itch]
# The Project URL you set when you created the game on Itch.io. https://my-username.itch.io/my-game.
# This will also be the name of your build files, so fill it out even if you aren't uploading to Itch.io.
url = "color-example"
# Your username on Itch.io.
username = "logankoester"
